version: 2

jobs:
  build:
    docker:
      - image: webgarden/php:7.1
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: composer run-script test:circle